version: '3.1'

services:
  postgres:
    build: ./
    restart: always
    networks:
      - db-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  web:
    build: ./web
    restart: always
    volumes:
      - ./web/dist:/app/dist
  server:
    build: ./server
    restart: always
    networks:
      - db-tier
      - back-tier
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/example
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./web/dist:/var/www/html
    networks:
      - back-tier
    ports:
      - 8080:80
networks:
  back-tier:
  db-tier:
